"""Merge the per-angle research JSON files in docs/research/ into one
deduplicated evidence file (docs/research/EVIDENCE.md) plus a flat
sources.csv. Run from the jj-simon-replication directory:

    python scripts/merge_research.py
"""
from __future__ import annotations

import csv
import glob
import json
import os
import re
from collections import OrderedDict

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "..", "docs", "research")


def norm(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", (s or "").lower()).strip()


def main() -> int:
    files = sorted(f for f in glob.glob(os.path.join(RES, "*.json")) if not f.endswith("firm_rules.json"))
    facts, numbers, sources, contradictions, questions = [], [], OrderedDict(), [], []
    seen_claims = set()
    per_angle = []
    for f in files:
        try:
            d = json.load(open(f))
        except Exception as e:  # noqa: BLE001
            print(f"skip {f}: {e}")
            continue
        if not isinstance(d, dict):
            print(f"skip {f}: not an angle file")
            continue
        angle = d.get("angle") or os.path.basename(f)[:-5]
        per_angle.append((angle, len(d.get("facts", [])), d.get("queries_run")))
        for x in d.get("facts", []):
            key = norm(x.get("claim", ""))[:120]
            if not key or key in seen_claims:
                continue
            seen_claims.add(key)
            x = dict(x)
            x["angle"] = angle
            facts.append(x)
        nums = d.get("numbers", [])
        if isinstance(nums, str):  # compact relay: a pointer sentence instead of rows
            nums = [{"name": "see", "value": nums, "context": "", "source_url": ""}]
        for n in nums:
            n = dict(n)
            n["angle"] = angle
            numbers.append(n)
        srcs = d.get("sources", [])
        if isinstance(srcs, str):
            srcs = []
        for s in srcs:
            u = (s.get("url") or "").strip()
            if u and u not in sources:
                sources[u] = s
        contradictions += [(angle, c) for c in d.get("contradictions", [])]
        questions += [(angle, q) for q in d.get("open_questions", [])]

    out = [
        "# Merged research evidence",
        "",
        "Generated by scripts/merge_research.py from the per-angle JSON files. Claims are deduplicated by wording; every line keeps its source URL. `JJ` marks JJ Simon's own words, `3rd` a third party.",
        "",
        "| angle | facts | queries |",
        "|---|---|---|",
    ]
    out += [f"| {a} | {n} | {q} |" for a, n, q in per_angle]
    out += ["", f"Totals: {len(facts)} distinct facts, {len(numbers)} numbers, {len(sources)} sources.", ""]

    out += ["## Facts", ""]
    for angle in OrderedDict.fromkeys(x["angle"] for x in facts):
        out += [f"### {angle}", ""]
        for x in (f for f in facts if f["angle"] == angle):
            who = "JJ" if x.get("jj_own_words") else "3rd"
            conf = x.get("confidence", "")
            date = f" ({x['date']})" if x.get("date") else ""
            line = f"- [{who}/{conf}] {x.get('claim','').strip()} [source]({x.get('source_url','')}){date}"
            out.append(line)
            if x.get("quote"):
                out.append(f"  > {x['quote'].strip()[:600]}")
        out.append("")

    out += ["## Numbers", "", "| name | value | context | angle | source |", "|---|---|---|---|---|"]
    for n in numbers:
        out.append(f"| {n.get('name','')} | {n.get('value','')} | {str(n.get('context',''))[:140]} | {n['angle']} | [link]({n.get('source_url','')}) |")

    out += ["", "## Contradictions", ""] + [f"- ({a}) {c}" for a, c in contradictions]
    out += ["", "## Open questions", ""] + [f"- ({a}) {q}" for a, q in questions]
    out += ["", "## Sources", "", "| kind | title | date | url |", "|---|---|---|---|"]
    for u, s in sources.items():
        out.append(f"| {s.get('kind','')} | {str(s.get('title',''))[:90]} | {s.get('date','')} | {u} |")

    with open(os.path.join(RES, "EVIDENCE.md"), "w") as fh:
        fh.write("\n".join(out) + "\n")
    with open(os.path.join(RES, "sources.csv"), "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["kind", "title", "date", "url"])
        for u, s in sources.items():
            w.writerow([s.get("kind", ""), s.get("title", ""), s.get("date", ""), u])
    print(f"{len(files)} files -> {len(facts)} facts, {len(numbers)} numbers, {len(sources)} sources")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
