"""Machine-check the extracted transcript facts against the primary corpus.

Every fact in docs/research/extracted/<video_id>.json carries a verbatim quote
and the line numbers it was taken from. This script re-reads the transcript,
confirms the quote really occurs (whitespace, case and punctuation
normalised), checks that it occurs within the cited lines, attaches an
approximate timestamp (position within the transcript times the video
duration) and writes:

  docs/research/extracted/_facts.json   every fact, flattened, with verification flags
  docs/research/EXTRACTED.md            verified facts grouped by topic, with citations

Usage (corpus = the private jj-simon-sources checkout):
  python3 scripts/verify_extracted.py /home/user/jj-simon-sources/jj-simon-replication/sources/youtube
"""
from __future__ import annotations

import glob
import json
import os
import re
import sys
from collections import Counter, defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
EXTRACTED = os.path.join(HERE, "..", "docs", "research", "extracted")
OUT_MD = os.path.join(HERE, "..", "docs", "research", "EXTRACTED.md")

TOPIC_ORDER = ["fair_value", "sessions_windows", "continuation", "reversion", "entry_trigger", "grading",
               "stops_targets_sizing", "rr_by_account", "risk_eval_vs_funded", "stop_trading_rules",
               "accounts_routing", "firm_rules_selection", "eval_math", "payout_rules_math", "results_claims",
               "backtest_stats", "news_trading", "execution_copier", "psychology_process", "business_mentorship", "other"]


def norm(s: str) -> str:
    return re.sub(r"[^a-z0-9$%.]+", " ", s.lower()).strip()


def mmss(seconds: float) -> str:
    seconds = int(round(seconds))
    h, m, s = seconds // 3600, (seconds % 3600) // 60, seconds % 60
    return f"{h}:{m:02d}:{s:02d}" if h else f"{m}:{s:02d}"


def load_transcript(corpus: str, vid: str):
    paths = glob.glob(os.path.join(corpus, f"*_{vid}_*.txt"))
    if not paths:
        return None
    lines = open(paths[0], errors="replace").read().split("\n")
    start = next((i for i, l in enumerate(lines) if l.strip() == "TRANSCRIPT"), 0) + 2
    duration = None
    info = os.path.join(corpus, "info", f"{vid}.info.json")
    if os.path.exists(info):
        try:
            duration = json.load(open(info)).get("duration")
        except Exception:  # noqa: BLE001
            duration = None
    return {"path": paths[0], "lines": lines, "start": start, "duration": duration,
            "norm_all": norm(" ".join(lines)), "title": lines[0].replace("TITLE: ", "") if lines else vid}


def main(corpus: str) -> int:
    facts_out = []
    per_video = {}
    for f in sorted(glob.glob(os.path.join(EXTRACTED, "*.json"))):
        if os.path.basename(f).startswith("_"):
            continue
        try:
            d = json.load(open(f))
        except Exception as e:  # noqa: BLE001
            print(f"skip {f}: {e}")
            continue
        vid = d.get("video_id") or os.path.basename(f)[:-5]
        tr = load_transcript(corpus, vid)
        if tr is None:
            print(f"no transcript for {vid}")
            continue
        n_ok = 0
        for x in d.get("facts", []):
            q = norm(x.get("quote", ""))
            ok = len(q) >= 12 and q in tr["norm_all"]
            a, b = int(x.get("line_start", 0) or 0), int(x.get("line_end", 0) or 0)
            lo, hi = max(1, min(a, b) - 3), max(a, b) + 3
            window = norm(" ".join(tr["lines"][lo - 1:hi]))
            line_ok = ok and q in window
            if ok and not line_ok:  # locate the real line so the citation can be repaired
                for i, l in enumerate(tr["lines"]):
                    if q[:40] in norm(" ".join(tr["lines"][i:i + 4])):
                        a = b = i + 1
                        line_ok = True
                        break
            frac = (max(a, tr["start"]) - tr["start"]) / max(1, len(tr["lines"]) - tr["start"])
            approx = mmss(frac * tr["duration"]) if tr["duration"] else None
            x.update({"video_id": vid, "video_title": tr["title"], "verified": ok, "line_verified": line_ok,
                      "line_start": a, "line_end": b, "approx_time": approx})
            facts_out.append(x)
            n_ok += ok
        per_video[vid] = (len(d.get("facts", [])), n_ok, tr["title"])
        json.dump(d, open(f, "w"), indent=1, ensure_ascii=False)
    os.makedirs(EXTRACTED, exist_ok=True)
    json.dump(facts_out, open(os.path.join(EXTRACTED, "_facts.json"), "w"), indent=1, ensure_ascii=False)

    total = len(facts_out)
    verified = [x for x in facts_out if x["verified"]]
    out = ["# Extracted primary-source facts (machine-verified quotes)", "",
           "Generated by scripts/verify_extracted.py from docs/research/extracted/*.json. Every quote below was found verbatim (after whitespace/case normalisation) in the transcript it cites. Citation: video id, approximate time (position in the transcript times the video duration, so +/- a few minutes), transcript line. Speaker JJ = JJ Simon; host = interviewer or sponsor read.",
           "", f"Totals: {total} facts extracted, {len(verified)} verified, {total - len(verified)} rejected.", "",
           "| video | title | facts | verified |", "|---|---|---|---|"]
    for vid, (n, k, title) in sorted(per_video.items(), key=lambda kv: -kv[1][0]):
        out.append(f"| {vid} | {title[:70]} | {n} | {k} |")
    out.append("")
    by_topic = defaultdict(list)
    for x in verified:
        by_topic[x.get("topic", "other")].append(x)
    for topic in TOPIC_ORDER + [t for t in by_topic if t not in TOPIC_ORDER]:
        xs = by_topic.get(topic)
        if not xs:
            continue
        out += [f"## {topic} ({len(xs)})", ""]
        for x in sorted(xs, key=lambda x: (x.get("speaker") != "JJ", x.get("confidence") != "high", x["video_id"])):
            t = f" ~{x['approx_time']}" if x.get("approx_time") else ""
            out.append(f"- [{x.get('speaker')}/{x.get('confidence')}] {x.get('claim','').strip()}")
            out.append(f"  > \"{x.get('quote','').strip()}\" ({x['video_id']}{t}, L{x['line_start']})")
        out.append("")
    rejected = [x for x in facts_out if not x["verified"]]
    if rejected:
        out += ["## Rejected (quote not found verbatim; review by hand)", ""]
        for x in rejected:
            out.append(f"- {x['video_id']} L{x['line_start']}: {x.get('claim','')[:160]}")
    open(OUT_MD, "w").write("\n".join(out) + "\n")
    spk = Counter(x.get("speaker") for x in verified)
    print(f"{len(per_video)} videos, {total} facts, {len(verified)} verified ({spk}); wrote EXTRACTED.md and _facts.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1]))
